version: '3.8'

networks:
  easygestao_network:
    driver: bridge

volumes:
  easygestao_database_data:

services:
  easygestao:
    container_name: easygestao
    build: .
    working_dir: /app/easygestao
    restart: unless-stopped
    tty: true
    ports:
      - '9000:9000'
    volumes:
      - ./:/app/easygestao
    networks:
      - easygestao_network

  mysql:
    container_name: mysql
    image: mysql:8.0
    networks:
      - easygestao_network
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: mysql
    volumes:
      - easygestao_database_data:/var/lib/mysql